#!/bin/bash
# Submit all dimer calculations
# Generated by generate_dimer_tests.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Submitting all dimer calculations..."
echo ""

cd h2 && qsub h2_dkh2.pbs && cd ..
cd li2 && qsub li2_dkh2.pbs && cd ..
cd be2 && qsub be2_dkh2.pbs && cd ..
cd b2 && qsub b2_dkh2.pbs && cd ..
cd c2 && qsub c2_dkh2.pbs && cd ..
cd n2 && qsub n2_dkh2.pbs && cd ..
cd o2 && qsub o2_dkh2.pbs && cd ..
cd f2 && qsub f2_dkh2.pbs && cd ..
cd na2 && qsub na2_dkh2.pbs && cd ..
cd mg2 && qsub mg2_dkh2.pbs && cd ..
cd al2 && qsub al2_dkh2.pbs && cd ..
cd si2 && qsub si2_dkh2.pbs && cd ..
cd p2 && qsub p2_dkh2.pbs && cd ..
cd s2 && qsub s2_dkh2.pbs && cd ..
cd cl2 && qsub cl2_dkh2.pbs && cd ..
cd k2 && qsub k2_dkh2.pbs && cd ..
cd ca2 && qsub ca2_dkh2.pbs && cd ..
cd sc2 && qsub sc2_dkh2.pbs && cd ..
cd ti2 && qsub ti2_dkh2.pbs && cd ..
cd v2 && qsub v2_dkh2.pbs && cd ..
cd cr2 && qsub cr2_dkh2.pbs && cd ..
cd mn2 && qsub mn2_dkh2.pbs && cd ..
cd fe2 && qsub fe2_dkh2.pbs && cd ..
cd co2 && qsub co2_dkh2.pbs && cd ..
cd ni2 && qsub ni2_dkh2.pbs && cd ..
cd cu2 && qsub cu2_dkh2.pbs && cd ..
cd zn2 && qsub zn2_dkh2.pbs && cd ..
cd ga2 && qsub ga2_dkh2.pbs && cd ..
cd ge2 && qsub ge2_dkh2.pbs && cd ..
cd as2 && qsub as2_dkh2.pbs && cd ..
cd se2 && qsub se2_dkh2.pbs && cd ..
cd br2 && qsub br2_dkh2.pbs && cd ..
cd y2 && qsub y2_dkh2.pbs && cd ..
cd zr2 && qsub zr2_dkh2.pbs && cd ..
cd nb2 && qsub nb2_dkh2.pbs && cd ..
cd mo2 && qsub mo2_dkh2.pbs && cd ..
cd tc2 && qsub tc2_dkh2.pbs && cd ..
cd ru2 && qsub ru2_dkh2.pbs && cd ..
cd rh2 && qsub rh2_dkh2.pbs && cd ..
cd pd2 && qsub pd2_dkh2.pbs && cd ..
cd ag2 && qsub ag2_dkh2.pbs && cd ..
cd cd2 && qsub cd2_dkh2.pbs && cd ..
cd in2 && qsub in2_dkh2.pbs && cd ..
cd sn2 && qsub sn2_dkh2.pbs && cd ..
cd sb2 && qsub sb2_dkh2.pbs && cd ..
cd te2 && qsub te2_dkh2.pbs && cd ..
cd i2 && qsub i2_dkh2.pbs && cd ..
cd hf2 && qsub hf2_dkh2.pbs && cd ..
cd ta2 && qsub ta2_dkh2.pbs && cd ..
cd w2 && qsub w2_dkh2.pbs && cd ..
cd re2 && qsub re2_dkh2.pbs && cd ..
cd os2 && qsub os2_dkh2.pbs && cd ..
cd ir2 && qsub ir2_dkh2.pbs && cd ..
cd pt2 && qsub pt2_dkh2.pbs && cd ..
cd au2 && qsub au2_dkh2.pbs && cd ..
cd hg2 && qsub hg2_dkh2.pbs && cd ..
cd tl2 && qsub tl2_dkh2.pbs && cd ..
cd pb2 && qsub pb2_dkh2.pbs && cd ..
cd bi2 && qsub bi2_dkh2.pbs && cd ..
cd po2 && qsub po2_dkh2.pbs && cd ..
cd at2 && qsub at2_dkh2.pbs && cd ..

echo "All jobs submitted!"
