#!/bin/bash
#
# generate_dimer_tests.sh
#
# Generates OpenMolcas DKH2 SCF input files and job scripts for homonuclear
# dimers across the periodic table (elements with MINAO data, up to Po).
#
# This is for studying IBO energy cutoffs for core/valence classification.
#
# Usage: ./generate_dimer_tests.sh [--submit]
#        --submit: Also submit all jobs via qsub after generation
#

set -e

# ============================================================================
# Configuration
# ============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="/home/joaschee/autoCAS4HE/tests/IBO_dimer_study"
PROJECT="starting_2025_097"
INSTALL_DIR="/dodrio/scratch/projects/${PROJECT}/autoCAS4HE_built/autoCAS4HE"
BASIS_SET="ANO-RCC-VDZP"

# Elements to skip (noble gases have very weak bonding)
# You can uncomment these to include them
SKIP_ELEMENTS="He Ne Ar Kr Xe Rn"

# ============================================================================
# Element Data (inline for portability)
# Format: element:Z:bond_angstrom:spin_multiplicity
# ============================================================================
read -r -d '' ELEMENT_DATA << 'EOF' || true
H:1:0.74:1
He:2:2.97:1
Li:3:2.67:1
Be:4:2.45:1
B:5:1.59:3
C:6:1.24:1
N:7:1.10:1
O:8:1.21:3
F:9:1.41:1
Ne:10:3.09:1
Na:11:3.08:1
Mg:12:3.89:1
Al:13:2.70:3
Si:14:2.25:3
P:15:1.89:1
S:16:1.89:3
Cl:17:1.99:1
Ar:18:3.76:1
K:19:3.92:1
Ca:20:4.28:1
Sc:21:2.60:5
Ti:22:1.94:3
V:23:1.77:3
Cr:24:1.68:1
Mn:25:3.40:1
Fe:26:2.02:7
Co:27:2.00:5
Ni:28:2.20:3
Cu:29:2.22:1
Zn:30:4.19:1
Ga:31:2.75:3
Ge:32:2.44:3
As:33:2.10:1
Se:34:2.17:3
Br:35:2.28:1
Kr:36:4.01:1
Y:39:2.85:5
Zr:40:2.24:3
Nb:41:2.08:3
Mo:42:1.93:1
Tc:43:2.13:3
Ru:44:2.28:7
Rh:45:2.28:5
Pd:46:2.48:3
Ag:47:2.53:1
Cd:48:4.07:1
In:49:3.01:3
Sn:50:2.75:3
Sb:51:2.34:1
Te:52:2.56:3
I:53:2.67:1
Xe:54:4.36:1
Hf:72:2.30:3
Ta:73:2.15:3
W:74:2.05:1
Re:75:2.24:3
Os:76:2.30:7
Ir:77:2.27:5
Pt:78:2.33:3
Au:79:2.47:1
Hg:80:3.69:1
Tl:81:3.00:3
Pb:82:2.93:3
Bi:83:2.66:1
Po:84:2.00:1
At:85:2.85:1
Rn:86:4.50:1
EOF

# ============================================================================
# Functions
# ============================================================================

should_skip() {
    local element=$1
    for skip in $SKIP_ELEMENTS; do
        if [[ "$element" == "$skip" ]]; then
            return 0
        fi
    done
    return 1
}

generate_xyz() {
    local element=$1
    local bond_length=$2
    local filename=$3

    local half=$(echo "scale=6; $bond_length / 2" | bc)
    local neg_half=$(echo "scale=6; -$bond_length / 2" | bc)

    cat > "$filename" << EOFXYZ
2
${element}2 molecule - ${bond_length} Angstrom bond
${element}  ${neg_half}   0.000000   0.000000
${element}   ${half}   0.000000   0.000000
EOFXYZ
}

generate_molcas_input() {
    local element=$1
    local spin=$2
    local xyz_file=$3
    local input_file=$4

    cat > "$input_file" << EOFINPUT
&GATEWAY
  Coord = ${xyz_file}
  Basis = ${BASIS_SET}
  Group = NoSym

&SEWARD
  Cholesky
* Douglas-Kroll-Hess 2nd order relativistic Hamiltonian
* Essential for heavy elements
  Relativistic = R02O

&SCF
  Charge = 0
  Spin = ${spin}
EOFINPUT
}

generate_pbs_script() {
    local element=$1
    local element_lower=$(echo "$element" | tr '[:upper:]' '[:lower:]')
    local dir=$2
    local spin=$3

    cat > "${dir}/${element_lower}2_dkh2.pbs" << EOFPBS
#!/bin/bash
# ${element}2 DKH2 relativistic HF calculation
# Generated by generate_dimer_tests.sh
#
#PBS -N ${element_lower}2_dkh2
#PBS -A 2025_127
#PBS -l nodes=1:ppn=8
#PBS -l walltime=02:00:00
#PBS -l mem=32gb
#PBS -M joachim.scheerlinck@ugent.be
#PBS -m e

# ==============================================================================
# Setup environment
# ==============================================================================
PROJECT="starting_2025_097"
INSTALL_DIR="/dodrio/scratch/projects/\${PROJECT}/autoCAS4HE_built/autoCAS4HE"
source \${INSTALL_DIR}/setup_hortense.sh
export MOLCAS_WORKDIR=\$(pwd)

cd \$PBS_O_WORKDIR

echo "=============================================="
echo "  ${element}2 DKH2 Relativistic HF Calculation"
echo "=============================================="
echo "Working directory: \$(pwd)"
echo "Date: \$(date)"
echo ""

# ==============================================================================
# Run OpenMolcas SCF for both geometries
# ==============================================================================
mkdir -p ${element_lower}2_0_workdir ${element_lower}2_1_workdir

# Geometry 0 (equilibrium)
echo "Running ${element}2 geometry 0 (equilibrium)..."
cd ${element_lower}2_0_workdir
cp ../${element_lower}2_0.xyz .
cp ../${element_lower}2_0_scf.input .
export MOLCAS_WORKDIR=\$(pwd)/scratch_0
mkdir -p \$MOLCAS_WORKDIR
pymolcas ${element_lower}2_0_scf.input > ${element_lower}2_0_scf.log 2>&1
if [ -f "${element_lower}2_0_scf/${element_lower}2_0_scf.scf.h5" ]; then
    cp ${element_lower}2_0_scf/${element_lower}2_0_scf.scf.h5 ../${element_lower}2_0.scf.h5
    echo "  Created ${element_lower}2_0.scf.h5"
else
    echo "WARNING: Could not find scf.h5 for geometry 0"
fi
cd ..

# Geometry 1 (stretched)
echo "Running ${element}2 geometry 1 (stretched)..."
cd ${element_lower}2_1_workdir
cp ../${element_lower}2_1.xyz .
cp ../${element_lower}2_1_scf.input .
export MOLCAS_WORKDIR=\$(pwd)/scratch_1
mkdir -p \$MOLCAS_WORKDIR
pymolcas ${element_lower}2_1_scf.input > ${element_lower}2_1_scf.log 2>&1
if [ -f "${element_lower}2_1_scf/${element_lower}2_1_scf.scf.h5" ]; then
    cp ${element_lower}2_1_scf/${element_lower}2_1_scf.scf.h5 ../${element_lower}2_1.scf.h5
    echo "  Created ${element_lower}2_1.scf.h5"
else
    echo "WARNING: Could not find scf.h5 for geometry 1"
fi
cd ..

# ==============================================================================
# Run IBO distribution analysis
# ==============================================================================
echo ""
echo "Running IBO distribution analysis..."
SCRIPT_DIR="${INSTALL_DIR}/scripts"
if [ -f "${element_lower}2_0.scf.h5" ]; then
    python3 \${SCRIPT_DIR}/IBO_distr.py ${element_lower}2_0.scf.h5 --element ${element_lower}
fi

echo ""
echo "=============================================="
echo "  ${element}2 calculation completed!"
echo "=============================================="
echo "Date: \$(date)"
EOFPBS

    chmod +x "${dir}/${element_lower}2_dkh2.pbs"
}

# ============================================================================
# Main
# ============================================================================

echo "=============================================="
echo "  Generating IBO Dimer Study Test Suite"
echo "=============================================="
echo ""

# Create base directory
mkdir -p "$BASE_DIR"

# Parse arguments
SUBMIT_JOBS=false
if [[ "$1" == "--submit" ]]; then
    SUBMIT_JOBS=true
fi

# Track generated elements
GENERATED=()
SKIPPED=()

# Process each element
while IFS=: read -r element z bond spin; do
    [[ -z "$element" ]] && continue

    if should_skip "$element"; then
        SKIPPED+=("$element")
        continue
    fi

    element_lower=$(echo "$element" | tr '[:upper:]' '[:lower:]')
    dir="${BASE_DIR}/${element_lower}2"

    echo "Generating ${element}2 (Z=${z}, spin=${spin})..."
    mkdir -p "$dir"

    # Calculate stretched bond length (2x equilibrium)
    bond_stretched=$(echo "scale=4; $bond * 2" | bc)

    # Generate XYZ files
    generate_xyz "$element" "$bond" "${dir}/${element_lower}2_0.xyz"
    generate_xyz "$element" "$bond_stretched" "${dir}/${element_lower}2_1.xyz"

    # Generate OpenMolcas input files
    generate_molcas_input "$element" "$spin" "${element_lower}2_0.xyz" "${dir}/${element_lower}2_0_scf.input"
    generate_molcas_input "$element" "$spin" "${element_lower}2_1.xyz" "${dir}/${element_lower}2_1_scf.input"

    # Generate PBS script
    generate_pbs_script "$element" "$dir" "$spin"

    GENERATED+=("$element")

done <<< "$ELEMENT_DATA"

# Generate master submission script
cat > "${BASE_DIR}/submit_all.sh" << 'EOFMASTER'
#!/bin/bash
# Submit all dimer calculations
# Generated by generate_dimer_tests.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Submitting all dimer calculations..."
echo ""

EOFMASTER

for element in "${GENERATED[@]}"; do
    element_lower=$(echo "$element" | tr '[:upper:]' '[:lower:]')
    echo "cd ${element_lower}2 && qsub ${element_lower}2_dkh2.pbs && cd .." >> "${BASE_DIR}/submit_all.sh"
done

echo "" >> "${BASE_DIR}/submit_all.sh"
echo 'echo "All jobs submitted!"' >> "${BASE_DIR}/submit_all.sh"
chmod +x "${BASE_DIR}/submit_all.sh"

# Generate analysis script
cat > "${BASE_DIR}/analyze_all.sh" << 'EOFANALYZE'
#!/bin/bash
# Analyze all completed dimer calculations
# Run IBO_distr.py on all .scf.h5 files

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Source environment
source ~/autoCAS4HE/setup_autocas_env.sh

echo "Analyzing all dimer calculations..."
echo ""

for dir in */; do
    element=$(basename "$dir" | sed 's/2$//')
    h5_file="${dir}${element}2_0.scf.h5"

    if [ -f "$h5_file" ]; then
        echo "Analyzing ${element}2..."
        cd "$dir"
        python3 ~/autoCAS4HE/scripts/IBO_distr.py "${element}2_0.scf.h5" --element "$element"
        cd ..
    fi
done

echo ""
echo "Analysis complete!"
EOFANALYZE
chmod +x "${BASE_DIR}/analyze_all.sh"

# Summary
echo ""
echo "=============================================="
echo "  Generation Complete!"
echo "=============================================="
echo ""
echo "Generated: ${#GENERATED[@]} dimer test directories"
echo "Skipped:   ${#SKIPPED[@]} elements (${SKIPPED[*]:-none})"
echo ""
echo "Output directory: $BASE_DIR"
echo ""
echo "Files created per element:"
echo "  - {element}2_0.xyz          (equilibrium geometry)"
echo "  - {element}2_1.xyz          (stretched geometry)"
echo "  - {element}2_0_scf.input    (OpenMolcas input)"
echo "  - {element}2_1_scf.input    (OpenMolcas input)"
echo "  - {element}2_dkh2.pbs       (PBS job script)"
echo ""
echo "Master scripts:"
echo "  - submit_all.sh             (submit all jobs)"
echo "  - analyze_all.sh            (run IBO analysis)"
echo ""

if $SUBMIT_JOBS; then
    echo "Submitting all jobs..."
    cd "$BASE_DIR"
    ./submit_all.sh
fi
